version: '3.8'
services:
  postgres:
    image: postgres:18
    container_name: crosspaynet-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: crosspaynet
      POSTGRES_USER: crosspaynet_user
      POSTGRES_PASSWORD: crosspaynet_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
